

export function positions(pos) {

    switch(pos) {
        case 0:
            return {gridColumn:"9",gridRow:"9"};
        case 1:
            return {gridColumn:"9",gridRow:"8"};
        case 2:
            return {gridColumn:"9",gridRow:"7"};
        case 3:
            return {gridColumn:"9",gridRow:"6"};
        case 4:
            return {gridColumn:"9",gridRow:"5"};
        case 5:
            return {gridColumn:"9",gridRow:"4"};
        case 6:
            return {gridColumn:"9",gridRow:"3"};
        case 7:
            return {gridColumn:"9",gridRow:"2"};
        case 8:
            return {gridColumn:"9",gridRow:"1"};
        case 9:
            return {gridColumn:"10",gridRow:"2"};
        case 10:
            return {gridColumn:"11",gridRow:"3"};
        case 11:
            return {gridColumn:"12",gridRow:"4"};
        case 12:
            return {gridColumn:"13",gridRow:"5"};
        case 13:
            return {gridColumn:"14",gridRow:"6"};
        case 14:
            return {gridColumn:"15",gridRow:"7"};
        case 15:
            return {gridColumn:"16",gridRow:"8"};
        case 16:
            return {gridColumn:"17",gridRow:"9"};
        case 17:
            return {gridColumn:"18",gridRow:"9"};
        case 18:
            return {gridColumn:"19",gridRow:"9"};
        case 19:
            return {gridColumn:"20",gridRow:"9"};
        case 20:
            return {gridColumn:"21",gridRow:"9"};
        case 21:
            return {gridColumn:"22",gridRow:"9"};
        case 22:
            return {gridColumn:"23",gridRow:"9"};
        case 23:
            return {gridColumn:"24",gridRow:"9"};
        case 24:
            return {gridColumn:"25",gridRow:"9"};
        case 25:
            return {gridColumn:"25",gridRow:"10"};
        case 26:
            return {gridColumn:"25",gridRow:"11"};
        case 27:
            return {gridColumn:"25",gridRow:"12"};
        case 28:
            return {gridColumn:"25",gridRow:"13"};
        case 29:
            return {gridColumn:"25",gridRow:"14"};
        case 30:
            return {gridColumn:"25",gridRow:"15"};
        case 31:
            return {gridColumn:"25",gridRow:"16"};
        case 32:
            return {gridColumn:"25",gridRow:"17"};
        case 33:
            return {gridColumn:"26",gridRow:"18"};
        case 34:
            return {gridColumn:"27",gridRow:"19"};
        case 35:
            return {gridColumn:"28",gridRow:"20"};
        case 36:
            return {gridColumn:"29",gridRow:"21"};
        case 37:
            return {gridColumn:"30",gridRow:"22"};
        case 38:
            return {gridColumn:"31",gridRow:"23"};
        case 39:
            return {gridColumn:"32",gridRow:"24"};
        case 40:
            return {gridColumn:"33",gridRow:"25"};
        case 41:
            return {gridColumn:"32",gridRow:"25"};
        case 42:
            return {gridColumn:"31",gridRow:"25"};
        case 43:
            return {gridColumn:"30",gridRow:"25"};
        case 44:
            return {gridColumn:"29",gridRow:"25"};
        case 45:
            return {gridColumn:"28",gridRow:"25"};
        case 46:
            return {gridColumn:"27",gridRow:"25"};
        case 47:
            return {gridColumn:"26",gridRow:"25"};
        case 48:
            return {gridColumn:"25",gridRow:"25"};
        case 49:
            return {gridColumn:"25",gridRow:"26"};
        case 50:
            return {gridColumn:"25",gridRow:"27"};
        case 51:
            return {gridColumn:"25",gridRow:"28"};
        case 52:
            return {gridColumn:"25",gridRow:"29"};
        case 53:
            return {gridColumn:"25",gridRow:"30"};
        case 54:
            return {gridColumn:"25",gridRow:"31"};
        case 55:
            return {gridColumn:"25",gridRow:"32"};
        case 56:
            return {gridColumn:"25",gridRow:"33"};
        case 57:
            return {gridColumn:"24",gridRow:"32"};
        case 58:
            return {gridColumn:"23",gridRow:"31"};
        case 59:
            return {gridColumn:"22",gridRow:"30"};
        case 60:
            return {gridColumn:"21",gridRow:"29"};
        case 61:
            return {gridColumn:"20",gridRow:"28"};
        case 62:
            return {gridColumn:"19",gridRow:"27"};
        case 63:
            return {gridColumn:"18",gridRow:"26"};
        case 64:
            return {gridColumn:"17",gridRow:"25"};
        case 65:
            return {gridColumn:"16",gridRow:"25"};
        case 66:
            return {gridColumn:"15",gridRow:"25"};
        case 67:
            return {gridColumn:"14",gridRow:"25"};
        case 68:
            return {gridColumn:"13",gridRow:"25"};
        case 69:
            return {gridColumn:"12",gridRow:"25"};
        case 70:
            return {gridColumn:"11",gridRow:"25"};
        case 71:
            return {gridColumn:"10",gridRow:"25"};
        case 72:
            return {gridColumn:"9",gridRow:"25"};
        case 73:
            return {gridColumn:"9",gridRow:"24"};      
        case 74:
            return {gridColumn:"9",gridRow:"23"};       
        case 75:
            return {gridColumn:"9",gridRow:"22"};        
        case 76:
            return {gridColumn:"9",gridRow:"21"};        
        case 77:
            return {gridColumn:"9",gridRow:"20"};       
        case 78:
            return {gridColumn:"9",gridRow:"19"};        
        case 79:
            return {gridColumn:"9",gridRow:"18"};        
        case 80:
            return {gridColumn:"9",gridRow:"17"};
        case 81:
            return {gridColumn:"8",gridRow:"16"};
        case 82:
            return {gridColumn:"7",gridRow:"15"};
        case 83:
            return {gridColumn:"6",gridRow:"14"};
        case 84:
            return {gridColumn:"5",gridRow:"13"};
        case 85:
            return {gridColumn:"4",gridRow:"12"};
        case 86:
            return {gridColumn:"3",gridRow:"11"};
        case 87:
            return {gridColumn:"2",gridRow:"10"};
        case 88:
            return {gridColumn:"1",gridRow:"9"};
        case 89:
            return {gridColumn:"2",gridRow:"9"};
        case 90:
            return {gridColumn:"3",gridRow:"9"};
        case 91:
            return {gridColumn:"4",gridRow:"9"};
        case 92:
            return {gridColumn:"5",gridRow:"9"};
        case 93:
            return {gridColumn:"6",gridRow:"9"};
        case 94:
            return {gridColumn:"7",gridRow:"9"};
        case 95:
            return {gridColumn:"8",gridRow:"9"};   
        case 96:
            return {gridColumn:"9",gridRow:"9"};
        default:
             return {gridColumn:"9",gridRow:"9"};
    }
}

